on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: docker/build-push-action@v2
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
        - uses: azure/setup-kubectl@v3
          with:
             version: 'v1.15.0' # default is latest stable
          id: install
