on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: docker/build-push-action@v3
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
